name: beme
channels:
  - plotly
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - argcomplete
  - argon2-cffi
  - attrs
  - backcall
  - backports
  - backports.functools_lru_cache
  - blas
  - bleach
  - bottleneck
  - brotlipy
  - bzip2
  - c-ares
  - ca-certificates
  - certifi
  - cffi
  - chardet
  - charset-normalizer
  - click
  - colorama
  - conda
  - conda-package-handling
  - cryptography
  - cycler
  - dash
  - dash-core-components
  - dash-html-components
  - dash-renderer
  - dash-table
  - dataclasses
  - dbus
  - debugpy
  - decorator
  - defusedxml
  - entrypoints
  - et_xmlfile
  - expat
  - flask
  - flask-compress
  - fontconfig
  - freetype
  - glib
  - gst-plugins-base
  - gstreamer
  - icu
  - idna
  - importlib-metadata
  - importlib_metadata
  - intel-openmp
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - itsdangerous
  - jedi
  - jinja2
  - jpeg
  - jsonschema
  - jupyter
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - jupyterlab_widgets
  - kiwisolver
  - krb5
  - ld_impl_linux-64
  - libarchive
  - libcurl
  - libedit
  - libev
  - libffi
  - libgcc-ng
  - libgfortran-ng
  - libgfortran4
  - libiconv
  - libnghttp2
  - libpng
  - libsodium
  - libsolv
  - libssh2
  - libstdcxx-ng
  - libuuid
  - libxcb
  - libxml2
  - llvm-openmp
  - lz4-c
  - lzo
  - mamba
  - markupsafe
  - matplotlib
  - matplotlib-base
  - matplotlib-inline
  - mistune
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - nbconvert
  - nbformat
  - ncurses
  - nest-asyncio
  - notebook
  - numexpr
  - numpy
  - numpy-base
  - openpyxl
  - openssl
  - packaging
  - pandas
  - pandocfilters
  - parso
  - patsy
  - pcre
  - pexpect
  - pickleshare
  - pip
  - plotly
  - prometheus_client
  - prompt-toolkit
  - prompt_toolkit
  - pthread-stubs
  - ptyprocess
  - pycosat
  - pycparser
  - pygments
  - pyopenssl
  - pyparsing
  - pyqt
  - pyrsistent
  - pysocks
  - python
  - python-dateutil
  - python_abi
  - pytz
  - pyzmq
  - qt
  - qtconsole
  - qtpy
  - readline
  - reproc
  - reproc-cpp
  - requests
  - ruamel_yaml
  - scipy
  - seaborn
  - send2trash
  - setuptools
  - sip
  - six
  - sqlite
  - statannotations
  - statsmodels
  - tenacity
  - terminado
  - testpath
  - tk
  - tornado
  - tqdm
  - traitlets
  - typing_extensions
  - upsetplot
  - urllib3
  - wcwidth
  - webencodings
  - werkzeug
  - wheel
  - widgetsnbextension
  - xorg-libxau
  - xorg-libxdmcp
  - xz
  - yaml
  - zeromq
  - zipp
  - zlib
  - zstd
